const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const GET_NEWS_SAGA = 'GET_NEWS_SAGA';
const SET_NEWS = 'SET_NEWS';
const GET_EVENTS_SAGA = 'GET_EVENTS_SAGA';
const SET_EVENTS = 'SET_EVENTS';
const GET_EXHIBITORS_SAGA = 'GET_EXHIBITORS_SAGA';
const SET_EXHIBITORS = 'SET_EXHIBITORS';
const GET_ARTISTS_SAGA = 'GET_ARTISTS_SAGA';
const SET_ARTISTS = 'SET_ARTISTS';
const GET_ARTWORKS_SAGA = 'GET_ARTWORKS_SAGA';
const SET_ARTWORKS = 'SET_ARTWORKS';
const GET_BLOCKS_SAGA = 'GET_BLOCKS_SAGA';
const SET_BLOCKS = 'SET_BLOCKS';

export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_NEWS_SAGA,
  SET_NEWS,
  GET_EVENTS_SAGA,
  SET_EVENTS,
  GET_EXHIBITORS_SAGA,
  SET_EXHIBITORS,
  GET_ARTISTS_SAGA,
  SET_ARTISTS,
  GET_ARTWORKS_SAGA,
  SET_ARTWORKS,
  GET_BLOCKS_SAGA,
  SET_BLOCKS
};
